name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "NOTICE"
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "NOTICE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.24.11
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run unit tests
        run: make tests
      - name: Upload code coverage
        uses: codecov/codecov-action@v5.3.1
        with:
          file: ./coverage.txt
      - name: Dry-run release snapshot
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: '~> v2'
          args: release --snapshot --skip publish --clean
